name: üßπ Cleaning up preview app
on: delete
jobs:
  delete:
    name: üßπ Cleaning up preview app
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gimlet-io/gimlet-cli:v0.25.0
    steps:
      - name: ‚¨áÔ∏è Check out
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 1
      - name: üßπ Cleaning up preview app
        env:
          GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
          GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}
        run: |
          apk add yq --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
          export SHA=$GITHUB_SHA
          echo ${{ github.event.ref }}
          export BRANCH=${GITHUB_EVENT_REF##refs/heads/}
          APP_NAME=$(gimlet manifest template -f .gimlet/first-fog-gais-preview.yaml | yq 'select(document_index == 1).metadata.name')
          echo Trying to delete $APP_NAME on preview
          gimlet release delete --env first-fog --app $APP_NAME
